impl SizeOf for some basic `std::net` types
Kixiron/size-of pull request #3
Opened 2022-10-27 08:15 UTC by little-dude

2022-10-27 09:32 UTC, little-dude commented
I'm not sure whether you're open to PRs to support more third-party crates. If so I have [a branch](https://github.com/Kixiron/size-of/compare/master...little-dude:size-of:ipnetwork) that adds support for the [`ipnetwork`](https://crates.io/crates/ipnetwork) crate.

2022-10-27 16:40 UTC, Kixiron requested changes

2022-10-27 16:40 UTC, Kixiron commented on src/tests/mod.rs
> +    }
```suggestion
    #[test]
    fn socket_addresses() {
        let ipv4 = Ipv4Addr::new(127, 0, 0, 1);
        assert_eq!(ipv4.size_of(), TotalSize::total(4));

        let ipv6 = Ipv6Addr::from_str("::1").unwrap();
        assert_eq!(ipv6.size_of(), TotalSize::total(16));

        let mut ip = IpAddr::V4(ipv4);
        assert_eq!(ip.size_of(), TotalSize::total(17));

        ip = IpAddr::V6(ipv6);
        assert_eq!(ip.size_of(), TotalSize::total(17));

        let addrv4 = SocketAddrV4::new(ipv4, 8080);
        assert_eq!(addrv4.size_of(), TotalSize::total(6));

        let addrv6 = SocketAddrV6::new(ipv6, 1, 2, 3);
        assert_eq!(addrv6.size_of(), TotalSize::total(28));

        let mut addr = SocketAddr::V4(addrv4);
        assert_eq!(addr.size_of(), TotalSize::total(32));

        addr = SocketAddr::V6(addrv6);
        assert_eq!(addr.size_of(), TotalSize::total(32));
    }
```

2022-10-27 18:20 UTC, little-dude commented on src/tests/mod.rs
> +    }
It does look better :) Applied

2022-11-07 14:31 UTC, little-dude commented
@Kixiron would you mind taking another look? I addressed you comment.

2022-11-07 17:37 UTC, Kixiron approved these changes
Awesome, thanks!

2022-11-07 17:37 UTC, merged

2022-11-07 17:41 UTC, Kixiron commented
And re `ipnetwork`, I'd gladly take a PR

2022-11-07 17:42 UTC, Kixiron commented
And re `ipnetwork`, I'd gladly take a PR